version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - redis
    environment:
      NODE_ENV: production
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgres://postgres:mysecretpassword@postgres:5432/postgres
      JWT_SECRET: ancasdadkjajsdlkasjdlaksjdasasdas
      PORT: 3000
      APP_URL: 'http://localhost:3000'
      GITHUB_CLIENT_ID: Ov23limdfUqNc9zzCTIn
      GITHUB_CLIENT_SECRET: 1f333a6072ab7c4153a9cb7727777c4e03d36120
      GITHUB_CALLBACK_URL: 'http://localhost:3000/auth/github/callback'
      CACHE_DEFAULT_TTL: 36000
      SQS_REGION: ap-southeast-1
      SQS_ACCESS_KEY_ID: AKIA5CBDRK6Y2QVESY7J
      SQS_SECRET_ACCESS_KEY: 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
      SQS_IS_FIFO: true
      SQS_QUEUE_NAME: DeployQueue.fifo
      SQS_URL: https://sqs.ap-southeast-1.amazonaws.com/897722701745/DeployQueue.fifo

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
