export const DOMAIN_PACK_STATUS = {
  WAITING: 'WAITING',
  ACTIVE: 'ACTIVE',
  FAILED: 'FAILED',
} as const;
export type DOMAIN_PACK_STATUS =
  (typeof DOMAIN_PACK_STATUS)[keyof typeof DOMAIN_PACK_STATUS];
export const BILLING_STATUS = {
  WAITING: 'WAITING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
} as const;
export type BILLING_STATUS =
  (typeof BILLING_STATUS)[keyof typeof BILLING_STATUS];
export const WEBHOOK_HTTP_METHODS = {
  GET: 'GET',
  POST: 'POST',
  PUT: 'PUT',
  DELETE: 'DELETE',
  PATCH: 'PATCH',
  OPTIONS: 'OPTIONS',
  HEAD: 'HEAD',
  CONNECT: 'CONNECT',
  TRACE: 'TRACE',
} as const;
export type WEBHOOK_HTTP_METHODS =
  (typeof WEBHOOK_HTTP_METHODS)[keyof typeof WEBHOOK_HTTP_METHODS];
export const WEBHOOK_EVENTS = {
  ON_START_PULL: 'ON_START_PULL',
  ON_DONE_PULL: 'ON_DONE_PULL',
  ON_START_BUILD: 'ON_START_BUILD',
  ON_DONE_BUILD: 'ON_DONE_BUILD',
  ON_FAILED_BUILD: 'ON_FAILED_BUILD',
  ON_START_DEPLOY: 'ON_START_DEPLOY',
  ON_DONE_DEPLOY: 'ON_DONE_DEPLOY',
  ON_FAILED_DEPLOY: 'ON_FAILED_DEPLOY',
} as const;
export type WEBHOOK_EVENTS =
  (typeof WEBHOOK_EVENTS)[keyof typeof WEBHOOK_EVENTS];
